from __future__ import annotations

import logging
import subprocess
from datetime import date
from pathlib import Path

from git import Repo

from dork.config import DorkConfig
from dork.models import ConventionDocEntry, ScoredPaper

log = logging.getLogger(__name__)


def create_pr(
    papers: list[ScoredPaper],
    rejected: list[ScoredPaper],
    file_paths: list[Path],
    config: DorkConfig,
    convention_entries: dict[str, list[ConventionDocEntry]] | None = None,
) -> int | None:
    kb_path = config.knowledge_base_path
    repo = Repo(str(kb_path))
    today = date.today().isoformat()
    branch_name = f"{config.output.branch_prefix}/{today}"

    # Create and checkout branch
    if branch_name in [ref.name for ref in repo.branches]:
        log.warning("branch already exists, using it", extra={"branch": branch_name})
        repo.git.checkout(branch_name)
    else:
        repo.git.checkout("-b", branch_name)

    # Stage all files (papers, articles, convention docs, index)
    for fp in file_paths:
        rel = fp.relative_to(kb_path)
        repo.index.add([str(rel)])

    repo.index.commit(f"dork: add {len(papers)} papers for {today}")

    # Push branch
    repo.git.push("origin", branch_name, "--set-upstream")

    # Build PR body
    pr_body = _build_pr_body(papers, rejected, convention_entries)

    # Create PR via gh CLI
    result = subprocess.run(
        [
            "gh", "pr", "create",
            "--repo", _get_remote_repo(repo),
            "--head", branch_name,
            "--title", f"dork: {len(papers)} papers for {today}",
            "--body", pr_body,
        ],
        capture_output=True,
        text=True,
        cwd=str(kb_path),
    )

    if result.returncode != 0:
        log.error("failed to create pr", extra={"stderr": result.stderr})
        return None

    # Extract PR number from URL
    pr_url = result.stdout.strip()
    log.info("created pr", extra={"url": pr_url})
    try:
        return int(pr_url.rstrip("/").split("/")[-1])
    except (ValueError, IndexError):
        return None


def _get_remote_repo(repo: Repo) -> str:
    for remote in repo.remotes:
        if remote.name == "origin":
            url = remote.url
            # Handle both HTTPS and SSH URLs
            if url.startswith("git@"):
                # git@github.com:user/repo.git
                path = url.split(":")[-1]
            elif "github.com" in url:
                # https://github.com/user/repo.git
                path = "/".join(url.split("github.com/")[-1].split("/")[:2])
            else:
                return url
            return path.removesuffix(".git")
    return ""


def _build_pr_body(
    accepted: list[ScoredPaper],
    rejected: list[ScoredPaper],
    convention_entries: dict[str, list[ConventionDocEntry]] | None = None,
) -> str:
    lines: list[str] = []

    # --- Primary: Convention doc changes ---
    if convention_entries:
        total_rules = sum(len(v) for v in convention_entries.values())
        lines.append("## Convention Doc Updates\n")
        lines.append(f"**{total_rules}** rules extracted → **{len(convention_entries)}** docs modified\n")
        for doc_path, entries in convention_entries.items():
            lines.append(f"### `{doc_path}`")
            for entry in entries:
                lines.append(f"- **{entry.section}**: {entry.rule[:120]}")
            lines.append("")

    # --- Secondary: Archive summaries ---
    lines.append("<details>")
    lines.append(f"<summary>Archive: {len(accepted)} papers/articles accepted</summary>\n")

    if accepted:
        for p in accepted:
            topics = ", ".join(p.relevance.topics[:3])
            update_badge = f" `UPDATED v{p.previous_version}→v{p.arxiv_version}`" if p.is_update else ""
            content_badge = f" `{p.content_type.value}`" if p.content_type.value != "paper" else ""
            lines.append(f"#### [{p.title[:80]}]({p.url}) — {p.relevance.score:.2f}{update_badge}{content_badge}")
            lines.append(f"**Topics:** {topics}")
            lines.append(f"> {p.relevance.reasoning}\n")

    lines.append("</details>\n")

    if rejected:
        lines.append("<details>")
        lines.append(f"<summary>Rejected ({len(rejected)}) — check to accept</summary>\n")
        for p in rejected:
            lines.append(f"- [ ] `{p.source_id}` **{p.title[:80]}** (score: {p.relevance.score:.2f}) — {p.relevance.reasoning[:100]}")
        lines.append("\n</details>")

    lines.append("\n---\nGenerated by [dork](https://github.com/rasha-hantash/dork)")
    return "\n".join(lines)
